/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const ScanLazyRouteImport = createFileRoute('/scan')()
const ProfileLazyRouteImport = createFileRoute('/profile')()
const LoginLazyRouteImport = createFileRoute('/login')()
const ImageSearchLazyRouteImport = createFileRoute('/image-search')()
const ForgotPasswordLazyRouteImport = createFileRoute('/forgot-password')()
const IndexLazyRouteImport = createFileRoute('/')()

const ScanLazyRoute = ScanLazyRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/scan.lazy').then((d) => d.Route))
const ProfileLazyRoute = ProfileLazyRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/profile.lazy').then((d) => d.Route))
const LoginLazyRoute = LoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const ImageSearchLazyRoute = ImageSearchLazyRouteImport.update({
  id: '/image-search',
  path: '/image-search',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/image-search.lazy').then((d) => d.Route))
const ForgotPasswordLazyRoute = ForgotPasswordLazyRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/forgot-password.lazy').then((d) => d.Route),
)
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/forgot-password': typeof ForgotPasswordLazyRoute
  '/image-search': typeof ImageSearchLazyRoute
  '/login': typeof LoginLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/scan': typeof ScanLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/forgot-password': typeof ForgotPasswordLazyRoute
  '/image-search': typeof ImageSearchLazyRoute
  '/login': typeof LoginLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/scan': typeof ScanLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/forgot-password': typeof ForgotPasswordLazyRoute
  '/image-search': typeof ImageSearchLazyRoute
  '/login': typeof LoginLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/scan': typeof ScanLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/image-search'
    | '/login'
    | '/profile'
    | '/scan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/image-search'
    | '/login'
    | '/profile'
    | '/scan'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/image-search'
    | '/login'
    | '/profile'
    | '/scan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ForgotPasswordLazyRoute: typeof ForgotPasswordLazyRoute
  ImageSearchLazyRoute: typeof ImageSearchLazyRoute
  LoginLazyRoute: typeof LoginLazyRoute
  ProfileLazyRoute: typeof ProfileLazyRoute
  ScanLazyRoute: typeof ScanLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-search': {
      id: '/image-search'
      path: '/image-search'
      fullPath: '/image-search'
      preLoaderRoute: typeof ImageSearchLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ForgotPasswordLazyRoute: ForgotPasswordLazyRoute,
  ImageSearchLazyRoute: ImageSearchLazyRoute,
  LoginLazyRoute: LoginLazyRoute,
  ProfileLazyRoute: ProfileLazyRoute,
  ScanLazyRoute: ScanLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
